<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
  </PropertyGroup>

  <PropertyGroup>
    <Product>Umbraco.Community.YouTubePicker</Product>
    <PackageId>Umbraco.Community.YouTubePicker</PackageId>
    <Title>Umbraco .Community .YouTube Picker</Title>
    <Description>Custom Umbraco datatype to enable editors to pick YouTube videos or playlists from a specific YouTube channel.</Description>
    <PackageTags>umbraco;umbraco-marketplace</PackageTags>
    <Authors>Ian Houghton</Authors>
    <Copyright>$([System.DateTime]::UtcNow.ToString(`yyyy`)) © Ian Houghton</Copyright>
    <PackageProjectUrl>https://github.com/redmorello/Umbraco.Community.YouTubePicker</PackageProjectUrl>
    <RepositoryUrl>https://github.com/redmorello/Umbraco.Community.YouTubePicker</RepositoryUrl>
    <PackageReadmeFile>README_nuget.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>https://raw.githubusercontent.com/redmorello/Umbraco.Community.YouTubePicker/64637700dee1b0be694a132e93936a39df358c2a/images/youtube.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="17.0.0-rc1" />
    <PackageReference Include="Umbraco.Cms.Web.Common" Version="17.0.0-rc1" />
    <PackageReference Include="Umbraco.Cms.Api.Common" Version="17.0.0-rc1" />
    <PackageReference Include="Umbraco.Cms.Api.Management" Version="17.0.0-rc1" />
  </ItemGroup>

  <ItemGroup>
    <!-- Dont include the client folder as part of packaging nuget build -->
    <Content Remove="Client\**" />

    <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
    <None Include="Client\public\umbraco-package.json" Pack="false" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\docs\README_nuget.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
