// This file is auto-generated by @hey-api/openapi-ts
import axios from 'axios';
import { YouTubeSearchResult } from '.';

export class UmbracoCommunityYouTubePickerService {

  public static Search(apiKey: string | undefined, searchType: string, channelId?: string, perPage?: number, term?: string | null, pageToken? : string | null): Promise<YouTubeSearchResult> {

    let key = apiKey !== undefined ? "&key=" + apiKey : '';
    let channel = channelId !== null && channelId !== "" && channelId !== undefined ? "&channelId=" + channelId : "";
    let type = "&type=" + searchType;
    let results = "&maxResults=" + (perPage !== undefined ? perPage : 50);
    let nextPage = pageToken !== undefined ? "&pageToken=" + pageToken : "";
    let query = term !== null && term !== undefined && term !== "" ? "&q=" + encodeURI(term) : "";

    //debugger;

    return new Promise<YouTubeSearchResult>((resolve, reject) => {

      let youTubeUrl = 'https://www.googleapis.com/youtube/v3/search?part=snippet' + key + channel + type + results + nextPage + query;
      console.log(youTubeUrl);
      axios.get<YouTubeSearchResult>(youTubeUrl)
        .then(function (response) {

          // not sure what this does !!
          resolve(response.data);
          return response;
        })
        .catch(function (error) {

          reject(error);
          // handle error
          console.log(error);
          return null;
        });
    })
  }
}
