name: Release Package

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:

    runs-on: windows-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Build and pack
      run: dotnet pack src\Umbraco.Community.YouTubePicker\Umbraco.Community.YouTubePicker.csproj -c Release /p:Version=${{github.ref_name}}

    - name: Push to GitHub NuGet
      run: dotnet nuget push **\*.nupkg -k ${{secrets.GITHUB_TOKEN}} -s https://nuget.pkg.github.com/redmorello/index.json

    - name: Push to NuGet
      run: |
        $oidcToken = (Invoke-RestMethod "$env:ACTIONS_ID_TOKEN_REQUEST_URL&audience=nuget.org" -Headers @{Authorization="bearer $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN"}).value
        $nugetToken = (Invoke-RestMethod "https://api.nuget.org/v1/trustedpublisher/oidctoken" -Method Post -ContentType "application/json" -Body (ConvertTo-Json @{oidcToken=$oidcToken})).tokenValue
        dotnet nuget push **\*.nupkg --api-key $nugetToken -s https://api.nuget.org/v3/index.json
      shell: pwsh
